if (typeof URL.canParse !== "function") {
  URL.canParse = function (url: string) {
    try {
      new URL(url);
      return true;
    } catch {
      return false;
    }
  };
}

import type { Metadata } from "next";
import "@/styles/globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased ${montserrat.className}`}>{children}</body>
    </html>
  );
}
